service: pivotal-friendly-numbers

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: ${opt:stage}
  environment:
    PIVOTAL_TOKEN: ${env:PIVOTAL_TOKEN}
    PROJECT_ID: ${env:PROJECT_ID}
    PGHOST: ${env:PGHOST}
    PGPASSWORD: ${env:PGPASSWORD}
    PGUSER: ${env:PGUSER}
    PGDATABASE: ${env:PGDATABASE}
    SERVICE_ACCOUNT_ID: ${env:SERVICE_ACCOUNT_ID}
    TICKET_PREFIX: ${env:TICKET_PREFIX}

functions:
  app:
    handler: index.main
    events:
      - http:
          path: /
          method: POST
          cors: true
      - http:
          path: /{proxy+}
          method: POST
          cors: true

plugins:
  - serverless-offline
